// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../app/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/backoffice/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backoffice/analytics">> = Specific
  const handler = {} as typeof import("../../app/backoffice/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/backoffice/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backoffice/audit">> = Specific
  const handler = {} as typeof import("../../app/backoffice/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/backoffice/cms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backoffice/cms">> = Specific
  const handler = {} as typeof import("../../app/backoffice/cms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/backoffice/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backoffice/events">> = Specific
  const handler = {} as typeof import("../../app/backoffice/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/backoffice/normalization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backoffice/normalization">> = Specific
  const handler = {} as typeof import("../../app/backoffice/normalization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/backoffice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backoffice">> = Specific
  const handler = {} as typeof import("../../app/backoffice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/backoffice/quality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backoffice/quality">> = Specific
  const handler = {} as typeof import("../../app/backoffice/quality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/backoffice/scrapers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backoffice/scrapers">> = Specific
  const handler = {} as typeof import("../../app/backoffice/scrapers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/backoffice/sync/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backoffice/sync">> = Specific
  const handler = {} as typeof import("../../app/backoffice/sync/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/backoffice/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backoffice/users">> = Specific
  const handler = {} as typeof import("../../app/backoffice/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cms">> = Specific
  const handler = {} as typeof import("../../app/cms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../app/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/normalization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/normalization">> = Specific
  const handler = {} as typeof import("../../app/normalization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/quality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quality">> = Specific
  const handler = {} as typeof import("../../app/quality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/scrapers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scrapers">> = Specific
  const handler = {} as typeof import("../../app/scrapers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sync/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sync">> = Specific
  const handler = {} as typeof import("../../app/sync/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../app/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/event-deactivate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/event-deactivate">> = Specific
  const handler = {} as typeof import("../../app/api/admin/event-deactivate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/events/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/events/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/events/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/events">> = Specific
  const handler = {} as typeof import("../../app/api/admin/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/genres/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/genres">> = Specific
  const handler = {} as typeof import("../../app/api/admin/genres/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/normalization/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/normalization">> = Specific
  const handler = {} as typeof import("../../app/api/admin/normalization/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/user-delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/user-delete">> = Specific
  const handler = {} as typeof import("../../app/api/admin/user-delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/user-role/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/user-role">> = Specific
  const handler = {} as typeof import("../../app/api/admin/user-role/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/user-upsert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/user-upsert">> = Specific
  const handler = {} as typeof import("../../app/api/admin/user-upsert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/user-verified/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/user-verified">> = Specific
  const handler = {} as typeof import("../../app/api/admin/user-verified/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync/trigger/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/trigger">> = Specific
  const handler = {} as typeof import("../../app/api/sync/trigger/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/backoffice/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/backoffice">> = Specific
  const handler = {} as typeof import("../../app/backoffice/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
